version: "2"

services:
  web:
    build: ./frontend/
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://api:8000
  api:
    build: ./backend/
    command: gunicorn --bind 0.0.0.0:8000 core.wsgi
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
